using System.Text.Json;
using MackySoft.Ucli.Application.Features.Requests.Shared.Preparation;
using MackySoft.Ucli.Application.Shared.Foundation;
using MackySoft.Ucli.Contracts.Ipc;
using MackySoft.Ucli.Contracts.Ipc.ContractReading;

namespace MackySoft.Ucli.Hosting.Cli.Requests;

/// <summary>Converts the public request DTO to the internal execute-arguments DTO.</summary>
internal sealed class UserRequestJsonNormalizer : IUserRequestJsonNormalizer
{
    /// <inheritdoc />
    public UserRequestJsonNormalizationResult Normalize (string requestJson)
    {
        if (string.IsNullOrWhiteSpace(requestJson))
        {
            return Failure("Request JSON must not be empty.");
        }

        try
        {
            using var document = JsonDocument.Parse(requestJson);
            if (document.RootElement.ValueKind != JsonValueKind.Object)
            {
                return Failure("Request JSON root must be an object.");
            }

            if (document.RootElement.TryGetProperty("protocolVersion", out _))
            {
                return Failure(
                    "Request property 'protocolVersion' is reserved and must not be specified. It is generated by the CLI.");
            }

            if (!IpcPayloadCodec.TryDeserializeStrict(
                    document.RootElement,
                    out UcliRequestJsonContract request,
                    out var payloadError))
            {
                return Failure($"Request JSON does not satisfy the request contract. {payloadError.Message}");
            }

            if (!UcliRequestJsonContractValidator.TryValidate(request, out _, out var validationError))
            {
                return Failure(validationError);
            }

            var executeArguments = new IpcExecuteArgumentsJsonContract
            {
                ProtocolVersion = IpcProtocol.CurrentVersion,
                Steps = request.Steps,
            };
            return UserRequestJsonNormalizationResult.Success(JsonSerializer.Serialize(
                executeArguments,
                IpcJsonSerializerOptions.StrictPropertyNames));
        }
        catch (JsonException exception)
        {
            return Failure($"Request JSON is invalid. {exception.Message}");
        }
    }

    private static UserRequestJsonNormalizationResult Failure (string message)
    {
        return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(message));
    }
}
