namespace MackySoft.Ucli.Contracts.Ipc.Validation;

/// <summary> Defines normalized machine-readable violation kinds for request-contract reads. </summary>
internal enum IpcRequestContractViolationKind
{
    None = 0,
    RequestMustBeObject,
    UnknownRequestProperty,
    ProtocolVersionMissing,
    ProtocolVersionTypeMismatch,
    RequestIdMissing,
    RequestIdTypeMismatch,
    RequestIdEmptyOrWhitespace,
    RequestIdOuterWhitespace,
    RequestIdFormatMismatch,
    StepsMissing,
    StepsTypeMismatch,
    StepMustBeObject,
    StepKindMissing,
    StepKindTypeMismatch,
    StepKindEmptyOrWhitespace,
    StepKindOuterWhitespace,
    StepKindUnsupported,
    UnknownStepProperty,
    StepIdMissing,
    StepIdTypeMismatch,
    StepIdEmptyOrWhitespace,
    StepIdOuterWhitespace,
    StepOpMissing,
    StepOpTypeMismatch,
    StepOpEmptyOrWhitespace,
    StepOpOuterWhitespace,
    StepArgsMissing,
    StepArgsTypeMismatch,
    StepOnMissing,
    StepOnTypeMismatch,
    StepSelectMissing,
    StepSelectTypeMismatch,
    StepActionsMissing,
    StepActionsTypeMismatch,
    StepActionMustBeObject,
    StepCommitMissing,
    StepCommitTypeMismatch,
    StepCommitEmptyOrWhitespace,
    StepCommitOuterWhitespace,
    DuplicatedStepId,
    Unknown,
}
