namespace MackySoft.Ucli.Contracts.Ipc.Validation;

/// <summary> Defines normalized machine-readable violation kinds for request-contract reads. </summary>
internal enum IpcRequestContractViolationKind
{
    None = 0,
    RequestMustBeObject,
    UnknownRequestProperty,
    ProtocolVersionMissing,
    ProtocolVersionTypeMismatch,
    RequestIdMissing,
    RequestIdTypeMismatch,
    RequestIdEmptyOrWhitespace,
    RequestIdOuterWhitespace,
    RequestIdFormatMismatch,
    OperationsMissing,
    OperationsTypeMismatch,
    OperationMustBeObject,
    UnknownOperationProperty,
    OperationIdMissing,
    OperationIdTypeMismatch,
    OperationIdEmptyOrWhitespace,
    OperationIdOuterWhitespace,
    OperationNameMissing,
    OperationNameTypeMismatch,
    OperationNameEmptyOrWhitespace,
    OperationNameOuterWhitespace,
    OperationArgsMissing,
    OperationArgsTypeMismatch,
    OperationAliasTypeMismatch,
    OperationAliasEmptyOrWhitespace,
    OperationAliasOuterWhitespace,
    ExpectationMustBeObject,
    ExpectationContainsUnknownProperty,
    ExpectationMustContainAtLeastOneConstraint,
    ExpectationBooleanConstraintMustBeBoolean,
    ExpectationIntegerConstraintMustBeInteger,
    ExpectationIntegerConstraintMustBeNonNegative,
    ExpectationCountCannotCombineWithMinOrMax,
    ExpectationMinMustBeLessThanOrEqualToMax,
    DuplicatedOperationId,
    Unknown,
}