using System;
using System.Text.Json;
using MackySoft.Ucli.Contracts.Ipc;
using MackySoft.Ucli.Contracts.Text;

#nullable enable

namespace MackySoft.Ucli.Unity.Execution.Requests
{
    /// <summary> Represents one normalized operation entry. </summary>
    public sealed class NormalizedOperation
    {
        /// <summary> Initializes a new instance of the <see cref="NormalizedOperation" /> class. </summary>
        /// <param name="ExecutionKey"> The request-local identity of this operation. </param>
        /// <param name="Op"> The operation name. </param>
        /// <param name="Args"> The normalized operation arguments JSON object. </param>
        /// <param name="As"> The optional alias exposed to later operations. </param>
        /// <param name="Expect"> The optional shared expectation constraints. </param>
        /// <param name="AliasReferences"> Typed identities for internal aliases serialized into this operation's arguments. </param>
        /// <param name="PersistenceReportingPolicy"> The public persistence reporting policy applied to phase results. </param>
        /// <param name="AllowExplicitPrefabAssetMutation"> Whether this operation may record request-attributed Prefab override changes that need an explicit target Prefab asset mutation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="ExecutionKey" />, <paramref name="Op" />, or <paramref name="AliasReferences" /> is <see langword="null" />. </exception>
        /// <exception cref="ArgumentException"> <paramref name="Op" />, <paramref name="Args" />, or <paramref name="AliasReferences" /> violates the normalized operation contract. </exception>
        /// <exception cref="ArgumentOutOfRangeException"> <paramref name="PersistenceReportingPolicy" /> is undefined. </exception>
        internal NormalizedOperation (
            OperationExecutionKey ExecutionKey,
            string Op,
            JsonElement Args,
            RequestLocalAliasIdentity? As,
            NormalizedExpectation? Expect,
            OperationAliasReferenceMap AliasReferences,
            OperationPersistenceReportingPolicy PersistenceReportingPolicy,
            bool AllowExplicitPrefabAssetMutation)
        {
            this.ExecutionKey = ExecutionKey ?? throw new ArgumentNullException(nameof(ExecutionKey));
            if (Op == null)
            {
                throw new ArgumentNullException(nameof(Op));
            }

            if (string.IsNullOrWhiteSpace(Op) || StringValueValidator.HasOuterWhitespace(Op))
            {
                throw new ArgumentException("Operation name must not be empty, whitespace, or surrounded by whitespace.", nameof(Op));
            }

            if (Args.ValueKind != JsonValueKind.Object)
            {
                throw new ArgumentException("Operation arguments must be a JSON object.", nameof(Args));
            }

            if (AliasReferences == null)
            {
                throw new ArgumentNullException(nameof(AliasReferences));
            }

            if (!ExecutionKey.IsEditPrimitive && AliasReferences.InternalAliasCount != 0)
            {
                throw new ArgumentException("Raw operations cannot reference aliases generated by edit lowering.", nameof(AliasReferences));
            }

            for (var index = 0; index < AliasReferences.InternalAliasCount; index++)
            {
                if (!AliasReferences[index].StepId.Equals(ExecutionKey.StepId))
                {
                    throw new ArgumentException("Internal alias references must belong to the operation's source step.", nameof(AliasReferences));
                }
            }

            if (PersistenceReportingPolicy != OperationPersistenceReportingPolicy.ReportAll
                && PersistenceReportingPolicy != OperationPersistenceReportingPolicy.SuppressAll
                && PersistenceReportingPolicy != OperationPersistenceReportingPolicy.SuppressScene)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(PersistenceReportingPolicy),
                    PersistenceReportingPolicy,
                    "Persistence reporting policy must be defined.");
            }

            this.Op = Op;
            this.Args = Args;
            this.As = As;
            this.Expect = Expect;
            this.AliasReferences = AliasReferences;
            this.PersistenceReportingPolicy = PersistenceReportingPolicy;
            this.AllowExplicitPrefabAssetMutation = AllowExplicitPrefabAssetMutation;
        }

        /// <summary> Identifies the public source-step kind that produced one primitive operation. </summary>
        public enum SourceStepKind
        {
            /// <summary> The primitive came from a raw <c>kind:"op"</c> step. </summary>
            Op = 0,

            /// <summary> The primitive came from a <c>kind:"edit"</c> lowering path. </summary>
            Edit = 1,
        }

        /// <summary> Gets the operation identifier. </summary>
        public IpcExecuteStepId Id => ExecutionKey.StepId;

        /// <summary> Gets the operation name. </summary>
        public string Op { get; }

        /// <summary> Gets the normalized operation arguments JSON object. </summary>
        public JsonElement Args { get; }

        /// <summary> Gets the optional alias exposed to later operations. </summary>
        internal RequestLocalAliasIdentity? As { get; }

        /// <summary> Gets the optional shared expectation constraints. </summary>
        public NormalizedExpectation? Expect { get; }

        /// <summary> Gets the request-local identity of this operation. </summary>
        internal OperationExecutionKey ExecutionKey { get; }

        /// <summary> Gets typed internal aliases referenced by serialized operation arguments. </summary>
        internal OperationAliasReferenceMap AliasReferences { get; }

        /// <summary> Gets a value indicating whether operation args may reference request-local aliases created by edit lowering. </summary>
        public bool AllowRequestLocalAliases => ExecutionKey.IsEditPrimitive;

        /// <summary> Gets the public source-step kind that produced this primitive operation. </summary>
        public SourceStepKind SourceKind => ExecutionKey.IsEditPrimitive
            ? SourceStepKind.Edit
            : SourceStepKind.Op;

        /// <summary> Gets the public persistence reporting policy applied to phase results. </summary>
        internal OperationPersistenceReportingPolicy PersistenceReportingPolicy { get; }

        /// <summary> Gets a value indicating whether explicit Prefab asset mutation fallback may be recorded for request-attributed override changes. </summary>
        public bool AllowExplicitPrefabAssetMutation { get; }
    }
}
