using System.Text;
using System.Text.Json;
using MackySoft.Ucli.Contracts.Ipc;
using MackySoft.Ucli.Shared.Foundation;

namespace MackySoft.Ucli.Features.Requests.Shared.Preparation;

/// <summary> Converts user-authored request JSON into the internal execute-request contract. </summary>
internal sealed class UserRequestJsonNormalizer : IUserRequestJsonNormalizer
{
    private const string StepsPropertyName = "steps";
    private const string ProtocolVersionPropertyName = "protocolVersion";
    private const string RequestIdPropertyName = "requestId";

    private readonly IRequestIdFactory requestIdFactory;

    /// <summary> Initializes a new instance of the <see cref="UserRequestJsonNormalizer" /> class. </summary>
    /// <param name="requestIdFactory"> The request identifier factory dependency. </param>
    public UserRequestJsonNormalizer (IRequestIdFactory requestIdFactory)
    {
        this.requestIdFactory = requestIdFactory ?? throw new ArgumentNullException(nameof(requestIdFactory));
    }

    /// <inheritdoc />
    public UserRequestJsonNormalizationResult Normalize (string requestJson)
    {
        if (string.IsNullOrWhiteSpace(requestJson))
        {
            return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(
                "Request JSON must not be empty."));
        }

        try
        {
            using var document = JsonDocument.Parse(requestJson);
            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(
                    "Request JSON root must be an object."));
            }

            foreach (var property in root.EnumerateObject())
            {
                if (string.Equals(property.Name, ProtocolVersionPropertyName, StringComparison.Ordinal)
                    || string.Equals(property.Name, RequestIdPropertyName, StringComparison.Ordinal))
                {
                    return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(
                        $"Request property '{property.Name}' is reserved and must not be specified. It is generated by the CLI."));
                }

                if (!string.Equals(property.Name, StepsPropertyName, StringComparison.Ordinal))
                {
                    return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(
                        $"Request contains an unknown property: {property.Name}."));
                }
            }

            return UserRequestJsonNormalizationResult.Success(CreateNormalizedRequestJson(root));
        }
        catch (JsonException exception)
        {
            return UserRequestJsonNormalizationResult.Failure(ExecutionError.InvalidArgument(
                $"Request JSON is invalid. {exception.Message}"));
        }
    }

    private string CreateNormalizedRequestJson (JsonElement root)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            writer.WriteStartObject();
            writer.WriteNumber(ProtocolVersionPropertyName, IpcProtocol.CurrentVersion);
            writer.WriteString(RequestIdPropertyName, requestIdFactory.Create());

            if (root.TryGetProperty(StepsPropertyName, out var stepsElement))
            {
                writer.WritePropertyName(StepsPropertyName);
                stepsElement.WriteTo(writer);
            }

            writer.WriteEndObject();
        }

        return Encoding.UTF8.GetString(stream.ToArray());
    }
}
