using MackySoft.Ucli.Application.Features.Testing.Run.Artifacts;

namespace MackySoft.Ucli.Features.Testing.Run.Execution;

/// <summary> Validates required test-run artifact files generated by Unity execution. </summary>
internal static class TestRunArtifactValidator
{
    /// <summary> Tries to validate required test-run artifact files exist. </summary>
    /// <param name="artifactPaths"> The run artifact paths. </param>
    /// <param name="errorMessage"> The validation error message when validation fails. </param>
    /// <returns> <see langword="true" /> when required artifacts exist; otherwise <see langword="false" />. </returns>
    public static bool TryValidateGeneratedFiles (
        ArtifactPaths artifactPaths,
        out string? errorMessage)
    {
        ArgumentNullException.ThrowIfNull(artifactPaths);

        if (!File.Exists(artifactPaths.ResultsXmlPath.Value))
        {
            errorMessage = $"Unity process completed but results.xml was not generated: {artifactPaths.ResultsXmlPath}";
            return false;
        }

        if (!File.Exists(artifactPaths.EditorLogPath.Value))
        {
            errorMessage = $"Unity process completed but editor.log was not generated: {artifactPaths.EditorLogPath}";
            return false;
        }

        errorMessage = null;
        return true;
    }
}
