using MackySoft.Ucli.Contracts.Execution.Lifecycle;

namespace MackySoft.Ucli.Application.Shared.Execution.Lifecycle;

/// <summary>
/// Carries the provider-neutral identity and timing that the application registration boundary
/// fixes before asking an execution provider to persist a Lifecycle Execution start record.
/// </summary>
internal sealed record LifecycleExecutionRegistration
{
    /// <summary> Initializes one pending Lifecycle Execution registration. </summary>
    public LifecycleExecutionRegistration (
        LifecycleExecutionDefinition definition,
        Guid executionId,
        DateTimeOffset deadlineUtc,
        DateTimeOffset startedAtUtc)
    {
        Definition = definition ?? throw new ArgumentNullException(nameof(definition));
        if (executionId == Guid.Empty)
        {
            throw new ArgumentException(
                "Lifecycle Execution identifier must not be empty.",
                nameof(executionId));
        }

        if (startedAtUtc == default || startedAtUtc.Offset != TimeSpan.Zero)
        {
            throw new ArgumentException(
                "Lifecycle Execution start time must be a non-default UTC timestamp.",
                nameof(startedAtUtc));
        }

        if (deadlineUtc == default || deadlineUtc.Offset != TimeSpan.Zero)
        {
            throw new ArgumentException(
                "Lifecycle Execution deadline must be a non-default UTC timestamp.",
                nameof(deadlineUtc));
        }

        if (deadlineUtc <= startedAtUtc)
        {
            throw new ArgumentOutOfRangeException(
                nameof(deadlineUtc),
                deadlineUtc,
                "Lifecycle Execution deadline must follow its start time.");
        }

        ExecutionId = executionId;
        DeadlineUtc = deadlineUtc;
        StartedAtUtc = startedAtUtc;
    }

    /// <summary> Gets the closed action definition whose canonical digest identifies this execution. </summary>
    public LifecycleExecutionDefinition Definition { get; }

    /// <summary> Gets the non-empty identifier generated by the application registration boundary. </summary>
    public Guid ExecutionId { get; }

    /// <summary> Gets the immutable execution deadline. </summary>
    public DateTimeOffset DeadlineUtc { get; }

    /// <summary> Gets the time at which the application registration boundary issued this registration. </summary>
    public DateTimeOffset StartedAtUtc { get; }

    /// <summary>
    /// Determines whether a provider reference identifies this registered logical execution.
    /// </summary>
    /// <param name="executionRef"> The provider reference to correlate. </param>
    /// <returns>
    /// <see langword="true" /> when kind, identifier, and definition digest all match;
    /// otherwise, <see langword="false" />.
    /// </returns>
    public bool HasSameIdentity (ExecutionRef executionRef)
    {
        ArgumentNullException.ThrowIfNull(executionRef);
        return executionRef.Kind == Definition.ExecutionKind
            && executionRef.Id == ExecutionId
            && executionRef.DefinitionDigest
                == LifecycleExecutionDefinitionDigest.Calculate(Definition);
    }
}
