namespace MackySoft.Ucli.Contracts.Ipc.ContractReading;

/// <summary> Defines normalized machine-readable violation kinds for <c>execute</c> arguments contract reads. </summary>
internal enum IpcExecuteArgumentsContractViolationKind
{
    None = 0,
    ArgumentsMustBeObject,
    UnknownArgumentsProperty,
    ProtocolVersionMissing,
    ProtocolVersionTypeMismatch,
    StepsMissing,
    StepsTypeMismatch,
    StepMustBeObject,
    StepKindMissing,
    StepKindTypeMismatch,
    StepKindEmptyOrWhitespace,
    StepKindOuterWhitespace,
    StepKindUnsupported,
    UnknownStepProperty,
    StepIdMissing,
    StepIdTypeMismatch,
    StepIdEmptyOrWhitespace,
    StepIdOuterWhitespace,
    StepOpMissing,
    StepOpTypeMismatch,
    StepOpEmptyOrWhitespace,
    StepOpOuterWhitespace,
    StepArgsMissing,
    StepArgsTypeMismatch,
    StepOnMissing,
    StepOnTypeMismatch,
    StepSelectMissing,
    StepSelectTypeMismatch,
    StepActionsMissing,
    StepActionsTypeMismatch,
    StepActionMustBeObject,
    StepCommitMissing,
    StepCommitTypeMismatch,
    StepCommitEmptyOrWhitespace,
    StepCommitOuterWhitespace,
    DuplicatedStepId,
    Unknown,
}
